/**
 * Pi Memory Extension — 3-layer persistent memory
 *
 * Layer 1: Session Memory — auto-extracted summary of current conversation, survives compaction
 * Layer 2: Auto-Memory — durable project knowledge in MEMORY.md, loaded every turn
 * Layer 3: Memory tool — explicit save/search/edit/clear by the LLM
 */

import * as path from "node:path";
import type { ExtensionAPI, ExtensionContext, Theme } from "@earendil-works/pi-coding-agent";
import { Type } from "@sinclair/typebox";
import { StringEnum } from "@earendil-works/pi-ai";
import { Text } from "@earendil-works/pi-tui";
import {
	getMemoryDir,
	getSessionMemoryDir,
	getEntrypointPath,
	getSessionMemoryPath,
	projectSlug,
	truncateContent,
	MAX_ENTRYPOINT_LINES,
	MAX_ENTRYPOINT_BYTES,
	MAX_SESSION_MEMORY_LINES,
	MAX_SESSION_MEMORY_BYTES,
	ensureDir,
	readFileContent,
	writeFileContent,
	listFiles,
	formatDate,
	parseFrontmatter,
} from "./storage.js";
import {
	extractFromTurn,
	formatSessionMemoryUpdate,
	formatAutoMemoryEntries,
	type ExtractionResult,
} from "./extractor.js";

// --- State ---

interface MemoryState {
	cwd: string;
	slug: string;
	sessionMemory: string;
	autoMemory: string;
	turnCount: number;
	injected: boolean;
	autoMemoryDirty: boolean;
	turnToolCalls: Array<{ name: string; input: Record<string, unknown>; output?: string }>;
}

let state: MemoryState | null = null;

function initState(cwd: string): MemoryState {
	return {
		cwd,
		slug: projectSlug(cwd),
		sessionMemory: "",
		autoMemory: "",
		turnCount: 0,
		injected: false,
		autoMemoryDirty: false,
		turnToolCalls: [],
	};
}

// --- System prompt injection ---

function buildMemoryBlock(sessionMemory: string, autoMemory: string): string {
	const parts: string[] = [];

	if (autoMemory.trim()) {
		parts.push("## Project Knowledge (persistent, from MEMORY.md)");
		parts.push(autoMemory.trim());
		parts.push("");
	}

	if (sessionMemory.trim()) {
		parts.push("## Session Context (auto-extracted this session)");
		parts.push(sessionMemory.trim());
	}

	if (parts.length === 0) return "";

	return `<pi-memory>\n${parts.join("\n")}\n</pi-memory>`;
}

// --- Session memory operations ---

async function loadSessionMemory(sessionFile: string | undefined): Promise<string> {
	const filePath = getSessionMemoryPath(sessionFile);
	if (!filePath) return "";
	const content = await readFileContent(filePath);
	return content || "";
}

async function saveSessionMemory(sessionFile: string | undefined, content: string): Promise<void> {
	const filePath = getSessionMemoryPath(sessionFile);
	if (!filePath) return;
	const truncated = truncateContent(content, MAX_SESSION_MEMORY_LINES, MAX_SESSION_MEMORY_BYTES);
	await writeFileContent(filePath, truncated.content);
}

// --- Auto-memory operations ---

async function loadAutoMemory(slug: string): Promise<string> {
	const entrypoint = getEntrypointPath(slug);
	const content = await readFileContent(entrypoint);
	return content || "";
}

async function saveAutoMemory(slug: string, content: string): Promise<void> {
	const entrypoint = getEntrypointPath(slug);
	const truncated = truncateContent(content, MAX_ENTRYPOINT_LINES, MAX_ENTRYPOINT_BYTES);
	await writeFileContent(entrypoint, truncated.content);
}

async function appendAutoMemoryTopics(
	slug: string,
	entries: Array<{ type: string; date: string; topics: string[]; content: string }>,
): Promise<void> {
	if (entries.length === 0) return;

	const memoryDir = getMemoryDir(slug);
	await ensureDir(memoryDir);

	let existing = await loadAutoMemory(slug);

	const additions: string[] = [];
	for (const entry of entries) {
		const topic = entry.topics[0] || "general";
		// Avoid duplicates
		if (!existing.includes(entry.content)) {
			additions.push(`- [${topic}] ${entry.content}`);
		}
	}

	if (additions.length === 0) return;

	if (!existing.trim()) {
		existing = `# Project Memory\n\nAuto-generated by Pi Memory Extension.\nKey facts, decisions, and patterns discovered while working on this project.\n\n`;
	}

	const today = formatDate();
	if (!existing.includes(`## ${today}`)) {
		existing += `\n## ${today}\n\n`;
	}

	existing += additions.join("\n") + "\n";

	await saveAutoMemory(slug, existing);
}

// --- Message extraction helper ---

function extractTextFromMessage(message: unknown): string {
	if (!message || typeof message !== "object") return "";
	const msg = message as Record<string, unknown>;

	// Handle { content: string }
	if (typeof msg.content === "string") return msg.content;

	// Handle { content: Array<{ type: "text", text: string }> }
	if (Array.isArray(msg.content)) {
		let text = "";
		for (const block of msg.content) {
			if (block && typeof block === "object" && block.type === "text" && typeof block.text === "string") {
				text += block.text + "\n";
			}
		}
		return text;
	}

	return "";
}

function extractContentFromToolResult(event: { content?: unknown }): string {
	if (!event.content) return "";
	if (typeof event.content === "string") return event.content;
	if (Array.isArray(event.content)) {
		let output = "";
		for (const block of event.content) {
			if (block && typeof block === "object" && block.type === "text" && typeof block.text === "string") {
				output += block.text;
			}
		}
		return output;
	}
	return "";
}

// --- Turn extraction ---

async function extractAndStore(
	pi: ExtensionAPI,
	ctx: ExtensionContext,
	assistantText: string,
	toolCalls: Array<{ name: string; input: Record<string, unknown>; output?: string }>,
): Promise<void> {
	if (!state) return;

	const extraction = extractFromTurn(assistantText, toolCalls);

	if (extraction.summary || extraction.decisions.length > 0) {
		const update = formatSessionMemoryUpdate(state.turnCount, extraction);
		state.sessionMemory += update;
		state.turnCount++;

		const sessionFile = ctx.sessionManager.getSessionFile();
		await saveSessionMemory(sessionFile, state.sessionMemory);
	}

	if (extraction.decisions.length > 0 || extraction.facts.length > 0) {
		const entries = formatAutoMemoryEntries(extraction);
		await appendAutoMemoryTopics(state.slug, entries);
		state.autoMemory = await loadAutoMemory(state.slug);
		state.autoMemoryDirty = true;
	}
}

// --- Tool call tracking ---

function trackToolCall(name: string, input: Record<string, unknown>): void {
	if (!state) return;
	state.turnToolCalls.push({ name, input });
}

function trackToolResult(name: string, output: string): void {
	if (!state) return;
	for (let i = state.turnToolCalls.length - 1; i >= 0; i--) {
		if (state.turnToolCalls[i].name === name && !state.turnToolCalls[i].output) {
			state.turnToolCalls[i].output = output.slice(0, 500);
			break;
		}
	}
}

// ═══════════════════════════════════════════════════════════════
// Main extension
// ═══════════════════════════════════════════════════════════════

export default function memoryExtension(pi: ExtensionAPI): void {

	// ── Tool: memory ──────────────────────────────────────────

	pi.registerTool({
		name: "memory",
		label: "Memory",
		description:
			"Manage persistent memory for this project. " +
			"Use 'save' to store important facts, decisions, or patterns. " +
			"Use 'search' to find relevant past memories. " +
			"Use 'show' to display current memories. " +
			"Use 'list' to list all memory topics. " +
			"Use 'clear' to delete all memories (destructive).",
		promptSnippet: "Save or retrieve persistent project memories",
		promptGuidelines: [
			"Use 'save' action when you discover important facts, decisions, or patterns the user should remember.",
			"Use 'search' action when you need to recall past decisions or project knowledge.",
			"Do NOT save trivial or obvious information.",
		],
		parameters: Type.Object({
			action: StringEnum(["save", "search", "show", "list", "edit", "clear"] as const),
			content: Type.Optional(Type.String({ description: "Content to save (for save/edit)" })),
			topic: Type.Optional(Type.String({ description: "Topic/category (for save/edit)" })),
			query: Type.Optional(Type.String({ description: "Search query (for search)" })),
		}),

		async execute(toolCallId, params, signal, onUpdate, ctx) {
			if (!state) {
				state = initState(ctx.cwd);
			}

			switch (params.action) {
				case "save": {
					if (!params.content) throw new Error("content is required for save action");
					const topic = params.topic || "general";
					await appendAutoMemoryTopics(state.slug, [{
						type: "learned",
						date: formatDate(),
						topics: [topic],
						content: params.content,
					}]);
					state.autoMemory = await loadAutoMemory(state.slug);
					state.sessionMemory += `**Saved**: [${topic}] ${params.content}\n`;
					return {
						content: [{ type: "text" as const, text: `✓ Saved to memory under "${topic}": ${params.content.slice(0, 100)}${params.content.length > 100 ? "..." : ""}` }],
						details: { action: "save", topic, content: params.content },
					};
				}

				case "search": {
					if (!params.query) throw new Error("query is required for search action");
					const allMemory = state.autoMemory + "\n" + state.sessionMemory;
					if (!allMemory.trim()) {
						return {
							content: [{ type: "text" as const, text: "No memories stored yet." }],
							details: { action: "search", query: params.query, results: 0 },
						};
					}
					const query = params.query.toLowerCase();
					const matches = allMemory.split("\n").filter((line) => line.toLowerCase().includes(query));
					if (matches.length === 0) {
						return {
							content: [{ type: "text" as const, text: `No memories matching "${params.query}".` }],
							details: { action: "search", query: params.query, results: 0 },
						};
					}
					return {
						content: [{ type: "text" as const, text: `Found ${matches.length} matching memories for "${params.query}":\n\n${matches.slice(0, 20).join("\n")}` }],
						details: { action: "search", query: params.query, results: matches.length },
					};
				}

				case "show": {
					const parts: string[] = [];
					if (state.autoMemory.trim()) {
						parts.push("=== Project Memory (MEMORY.md) ===\n");
						parts.push(state.autoMemory);
					}
					if (state.sessionMemory.trim()) {
						parts.push("\n=== Session Memory ===\n");
						parts.push(state.sessionMemory);
					}
					if (parts.length === 0) parts.push("No memories stored yet.");
					return {
						content: [{ type: "text" as const, text: parts.join("\n") }],
						details: { action: "show" },
					};
				}

				case "list": {
					const memoryDir = getMemoryDir(state.slug);
					const files = await listFiles(memoryDir);
					if (files.length === 0) {
						return {
							content: [{ type: "text" as const, text: "No memory files. Use 'save' to create one." }],
							details: { action: "list", files: [] as string[] },
						};
					}
					const listing = files.slice(0, 20).map((f) => `- ${f}`).join("\n");
					return {
						content: [{ type: "text" as const, text: `Memory files:\n${listing}` }],
						details: { action: "list", files },
					};
				}

				case "edit": {
					if (!params.content) throw new Error("content is required for edit action");
					await saveAutoMemory(state.slug, params.content);
					state.autoMemory = params.content;
					return {
						content: [{ type: "text" as const, text: "✓ Memory updated." }],
						details: { action: "edit" },
					};
				}

				case "clear": {
					const entrypoint = getEntrypointPath(state.slug);
					await writeFileContent(entrypoint, "");
					state.autoMemory = "";
					const sessionFile = ctx.sessionManager.getSessionFile();
					const sessionPath = getSessionMemoryPath(sessionFile);
					if (sessionPath) await writeFileContent(sessionPath, "");
					state.sessionMemory = "";
					return {
						content: [{ type: "text" as const, text: "✓ All memories cleared." }],
						details: { action: "clear" },
					};
				}

				default:
					throw new Error(`Unknown action: ${(params as { action: string }).action}`);
			}
		},

		renderCall(args, theme) {
			const actionColorMap: Record<string, string> = {
				save: "success", search: "accent", show: "muted",
				list: "muted", edit: "warning", clear: "error",
			};
			const color = actionColorMap[args.action] || "muted";
			let text = theme.fg("toolTitle" as any, theme.bold("memory "));
			text += theme.fg(color as any, args.action);
			if (args.content) {
				const preview = args.content.length > 50 ? args.content.slice(0, 50) + "…" : args.content;
				text += " " + theme.fg("dim" as any, `"${preview}"`);
			}
			if (args.query) {
				text += " " + theme.fg("dim" as any, `"${args.query}"`);
			}
			return new Text(text, 0, 0);
		},

		renderResult(result, { expanded }, theme) {
			const details = result.details as Record<string, unknown> | undefined;
			const action = (details?.action as string) || "";
			if (details?.error) {
				return new Text(theme.fg("error" as any, `Error: ${details.error}`), 0, 0);
			}
			if (action === "save") {
				return new Text(theme.fg("success" as any, "✓ Memory saved"), 0, 0);
			}
			if (action === "search") {
				const count = (details?.results as number) || 0;
				return new Text(theme.fg("accent" as any, `✓ Found ${count} result${count !== 1 ? "s" : ""}`), 0, 0);
			}
			if (action === "clear") {
				return new Text(theme.fg("warning" as any, "✓ Memory cleared"), 0, 0);
			}
			return new Text(theme.fg("success" as any, "✓ Done"), 0, 0);
		},
	});

	// ── Command: /memory ──────────────────────────────────────

	pi.registerCommand("memory", {
		description: "Browse and manage project memory (show, edit, clear)",
		handler: async (args, ctx) => {
			if (!state) {
				state = initState(ctx.cwd);
			}

			const subcommand = args.trim().toLowerCase();

			if (subcommand === "clear") {
				const ok = await ctx.ui.confirm("Clear all memory?", "This will delete all saved memories for this project.");
				if (ok) {
					const entrypoint = getEntrypointPath(state.slug);
					await writeFileContent(entrypoint, "");
					state.autoMemory = "";
					state.sessionMemory = "";
					ctx.ui.notify("Memory cleared", "info");
				}
				return;
			}

			if (subcommand === "edit") {
				const current = state.autoMemory || "# Project Memory\n\n";
				const edited = await ctx.ui.editor("Edit MEMORY.md:", current);
				if (edited !== undefined && edited !== null) {
					await saveAutoMemory(state.slug, edited);
					state.autoMemory = edited;
					ctx.ui.notify("Memory updated", "info");
				}
				return;
			}

			// Default: show memory content
			const content = "=== Project Memory ===\n\n" +
				(state.autoMemory || "(empty)") +
				"\n\n=== Session Memory ===\n\n" +
				(state.sessionMemory || "(empty)");

			const lines = content.split("\n");
			// Notify with a summary for non-interactive use
			ctx.ui.notify(
				`Memory: ${state.autoMemory.split("\n").length} lines project, ${state.sessionMemory.split("\n").length} lines session. Use /memory edit to modify.`,
				"info",
			);
		},
	});

	// ── Event: session_start ──────────────────────────────────

	pi.on("session_start", async (_event, ctx) => {
		state = initState(ctx.cwd);
		state.autoMemory = await loadAutoMemory(state.slug);
		const sessionFile = ctx.sessionManager.getSessionFile();
		state.sessionMemory = await loadSessionMemory(sessionFile);

		if (state.autoMemory || state.sessionMemory) {
			const autoLines = state.autoMemory.split("\n").length;
			const sessionLines = state.sessionMemory.split("\n").length;
			ctx.ui.notify(
				`🧠 Memory loaded: ${autoLines} lines project, ${sessionLines} lines session`,
				"info",
			);
		}
	});

	// ── Event: before_agent_start ─────────────────────────────

	pi.on("before_agent_start", async (event, _ctx) => {
		if (!state) return;
		const memoryBlock = buildMemoryBlock(state.sessionMemory, state.autoMemory);
		if (!memoryBlock) return;
		state.injected = true;
		return { systemPrompt: event.systemPrompt + "\n\n" + memoryBlock };
	});

	// ── Event: turn_end ───────────────────────────────────────

	pi.on("turn_end", async (event, ctx) => {
		if (!state) return;

		const assistantText = extractTextFromMessage(event.message);
		if (assistantText.trim().length > 20 || state.turnToolCalls.length > 0) {
			await extractAndStore(pi, ctx, assistantText, state.turnToolCalls);
		}
		state.turnToolCalls = [];
	});

	// ── Event: tool_call ──────────────────────────────────────

	pi.on("tool_call", async (event, _ctx) => {
		if (!state) return;
		trackToolCall(event.toolName, event.input as Record<string, unknown>);
	});

	// ── Event: tool_result ────────────────────────────────────

	pi.on("tool_result", async (event, _ctx) => {
		if (!state) return;
		const output = extractContentFromToolResult(event as { content?: unknown });
		trackToolResult(event.toolName, output);
	});

	// ── Event: session_before_compact ─────────────────────────

	pi.on("session_before_compact", async (_event, ctx) => {
		if (!state) return;
		const sessionFile = ctx.sessionManager.getSessionFile();
		await saveSessionMemory(sessionFile, state.sessionMemory);
	});

	// ── Event: session_compact ────────────────────────────────

	pi.on("session_compact", async (_event, _ctx) => {
		if (!state) return;
		// Memory is persisted to disk; auto-memory survives compaction naturally.
		// Session memory will be re-attached via before_agent_start next turn.
	});

	// ── Event: session_shutdown ───────────────────────────────

	pi.on("session_shutdown", async (_event, ctx) => {
		if (!state) return;
		const sessionFile = ctx.sessionManager?.getSessionFile();
		if (sessionFile && state.sessionMemory) {
			await saveSessionMemory(sessionFile, state.sessionMemory);
		}
		if (state.autoMemoryDirty && state.autoMemory) {
			await saveAutoMemory(state.slug, state.autoMemory);
		}
	});
}
